# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnimedia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1000)),
                ('media_type', models.CharField(choices=[('AUD', 'Audiobook'), ('MOV', 'Movie'), ('MUS', 'Music')], max_length=3)),
            ],
        ),
    ]
