# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnimedia', '0003_whitelist_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafolder',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
